services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_tmdt
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: tmdt
      RABBITMQ_DEFAULT_PASS: tmdt2026
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ✅ MySQL (1 container)
  mysql:
    image: mysql:8
    container_name: mysql_tmdt
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: tmdt
        HAS_PRISMA: "false"
    container_name: api_gateway_tmdt
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://tmdt:tmdt2026@rabbitmq:5672

  # User service
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: user-service
        HAS_PRISMA: "true"
    container_name: user_service_tmdt
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://tmdt:tmdt2026@rabbitmq:5672
      DATABASE_URL: mysql://root:password@mysql:3306/db_users

  # Review service
  review-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: review-service
        HAS_PRISMA: "true"
    container_name: review_service_tmdt
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      RABBITMQ_URL: amqp://tmdt:tmdt2026@rabbitmq:5672
      DATABASE_URL: mysql://root:password@mysql:3306/db_reviews

  # Inventory service
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: inventory-service
        HAS_PRISMA: "false"
    container_name: inventory_service_tmdt
    restart: unless-stopped
    ports:
      - "3004:3004"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: production
      INVENTORY_SERVICE_PORT: 3004
      RABBITMQ_URL: amqp://tmdt:tmdt2026@rabbitmq:5672
      DATABASE_URL: mysql://root:password@mysql:3306/db_inventory


volumes:
  mysql_data: